x-base_service: &base_service
    init: true
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - ./data:/data
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu, compute, utility]

services:
  download:
    container_name: download
    volumes:
      - ./data:/data
    profiles: ["download"]
    build: ./services/download/
  download_simple:
    container_name: download_simple
    volumes:
      - ./data_simple:/data_simple
    profiles: ["download_simple"]
    build: ./services/download_simple/

  comfy:
    <<: *base_service
    container_name: comfy
    profiles: ["comfy"]
    build: ./services/comfy/
    image: "comfy:comfy"
    environment:
      - CLI_ARGS=

  comfy_simple:
    container_name: comfy_simple
    profiles: ["comfy_simple"]
    build: ./services/comfy_simple/
    image: "comfy_simple:comfy_simple"
    environment:
      - CLI_ARGS=
    volumes:
      - ./data_simple:/data_simple
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu, compute, utility]
